### ISSUE TITLE
用户登录系统

### ISSUE THREAD

**Issue by Tsumugi52961** [Tsumugi52961/bangumi_noticer#2]
User Model:
 - name
 - email

Controller:
 - 父类中加入current_user方法，根据参数获取当前用户。
 - 调用API获取番组时中先尝试current_user, <del>如果获取不到则创建新用户</del>
 - 其他需要验证登录的情况，e.g. Subscription#create

**Comment by xlres** [comment]
现在API的父类是ApplicationController, 想办法换成Api::V1::BaseApiController, 从ActionController::Metal 继承。然后在BaseApiController中添加current_user方法。
其他需要include的东西，以及其他通用的方法等等也考虑在这里添加

**Comment by Tsumugi52961** [comment]
想了一下还是用 ActionController::Base 好了，以后有需要再换Metal自己定制。
<del>不要吐槽我换号。</del>

**Comment by Tsumugi52961** [comment]
获取不到就创建新用户这事儿还是和前端结合起来比较好，虽然现在只有 name 没有 password。如果发现根据 name 和 email 获取不到User就先返回 400/404.
如果先加入 password 再有前端就忘了吧……
