### ISSUE TITLE
用其他的技术方案重新开始

### ISSUE THREAD

**Issue by Tsumugi52961** [Tsumugi52961/bangumi_noticer#20]
由于 #15 中提到的，乞丐版搬瓦工跑不动 Rails, 想想以后估计也不可能月供 $10 或者更多去养个玩具，现在在考虑用其他更轻型的框架来实现 API.

暂时的想法是用 rainbows / puma 跑纯 grape，专注于 API 而放弃渲染 web 页面。好处是省资源，就算是内存不到 200M 的破 VPS 也能稳定跑起来，坏处是前后端分离的这么彻底（两台服务器）要重新考虑 web 端怎么做，以及额外的学习成本。虽然 web 可能要跑在别的地方，不过那也是以后的事了。

然而今天看了一天，仍然不是很懂 Grape. 过去 Rails 包办一切不操心，现在很多工具和配置要自己写，有些原理上的东西不知道，看着官方 wiki 和 examples 也不知道如何下手。再加上之后一段时间各种事，不知道下次再开是什么时候。

**Comment by Matrixbirds** [comment]
为何不用rails 5 api

**Comment by Tsumugi52961** [comment]
写着玩儿的东西有人关注真是开心啊。

这个项目主要是为了练(hao) 手(wan)，服务能不能起来倒是其次，包括现在折腾 Grape 也是，确实发现了很多过去局限的地方<del>玩的很开心</del>。

所以现在还是打算先继续 Grape，过一段时间弄完了毕业论文再来感受一下 API-only 的 Rails.

感谢建议。
