### ISSUE TITLE
登录时需要密码

### ISSUE THREAD

**Issue by Tsumugi52961** [Tsumugi52961/bangumi_noticer#4]
用户登录时需要密码，数据库中储存密码的 hash.
登录后生成 token，作为调用 api 时验证的凭据。

User Model:
 - <del>add column: password (or password_hash / password_digest ?)</del> password_digest existed

Base Api Controller: 
 - Action: #restrict_access (and other related actions...)

(new) ApiKey Model:
 - token
 - expired_at
 - user_id
 - ...

**Comment by xlres** [comment]
刚刚知道有一个挺有意思的 gem 叫 devise， 似乎可以直接用来做用户注册、登录、验证等等。.
为什么没有早点发现呢……

**Comment by Tsumugi52961** [comment]
大致了解了一下关于用户管理的解决方案。

目前有一种很流行的方案是使用 devise + cancan + rolify, 应该可以满足大部分情境的要求。但也有反对的意见，认为 devise 过于复杂，定制化也相当麻烦，提倡尽量用原生的 SecurePassword 等等来搭建用户系统。这里打算用原生的试一试。

至于 cancan 和 rolify, 目前用不到很复杂的权限系统所以先放一放，同样是原生的 before_filter 应该可以满足要求，以后如果功能上有需求再来考虑。

**Comment by Tsumugi52961** [comment]
说明一下。

关于烦恼了很久的登录流程安全性问题，这里直接使用了 SecurePassword 在服务器端为用户密码加密，客户端直接以邮箱和密码访问 /auth/token 验证身份，确认之后可以获得 token. 理想的流程中调用其它需要登录的 API 需要以这个 token 作为凭证，不过现在只是新增了 secure password 和 token 系统，没有改造原有的 API。

用密码换取 token 的 API，本来想采用安全性更高一点的方案，但似乎在使用 http 协议而不是 https 或者 ssl 的情况下无论如何没太大卵用，所以就只做了一个简单的实现。如果以后发现有问题一定要换更好的方式。

有些 web app 中把 token 放在 user 表中，这里使用了单独创建一个 api_key 关联到 user 的做法。api_key 设置的过期时间为 30 天，如果发现过期可以再次创建一个新的 api_key 关联到 user. 这里常用的做法似乎是更新 api_key 中 access_token 字段，不过每年每个用户新创建 12 个 api_key 应该算不上什么负担……何况过期的会被自动删除。 

剩下的工作就是给 api 装上 token 验证机制，还有处理 token 过期和清理过期 api_key.
